#db config
quarkus.datasource.db-kind=mysql
quarkus.datasource.reactive=true
quarkus.datasource.username=root
quarkus.datasource.password=root
quarkus.datasource.reactive.url=mysql://localhost:3306/practise
#quarkus.datasource.reactive.url=mysql://mysql:3306/practise

#quarkus.hibernate-orm.database.generation=update
#quarkus.hibernate-orm.log.sql=true

quarkus.http.port=9990

#quarkus.native.container-build=true
#quarkus.native.builder-image=quay.io/quarkus/ubi-quarkus-mandrel-builder-image:22.3-java17

# Enable Swagger
quarkus.smallrye-openapi.path=/openapi
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/swagger-ui

#quarkus.package.type=jar


